from paralex import paralex_factory

package = paralex_factory("LeFFI",
                          {
                              "forms": {"path": "LeFFI_forms.csv",},
                              "cells": {"path": "LeFFI_cells.csv"},
                              "features-values": {"path": "LeFFI_features-values.csv"},
                              "sounds": {"path": "LeFFI_sounds.csv",
                                "schema": {
                                   "fields": 
                                    [{'name': 'tier',
                                      'title': 'Tier to which the feature pertains',
                                      'description': 'Tier to which the feature pertains',
                                      'type': 'string',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'value',
                                      'title': 'Value of the feature',
                                      'description': 'Value of the feature for non segmental tiers',
                                      'type': 'string',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'close_consonantal',
                                      'title': 'Whether the sound displays the feature [close_consonantal]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [close_consonantal]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'open',
                                      'title': 'Whether the sound displays the feature [open]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [open]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'labial_consonantal',
                                      'title': 'Whether the sound displays the feature [labial_consonantal]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [labial_consonantal]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'labiodental',
                                      'title': 'Whether the sound displays the feature [labiodental]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [labiodental]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'coronal_consonantal',
                                      'title': 'Whether the sound displays the feature [coronal_consonantal]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [coronal_consonantal]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'dorsal_consonantal',
                                      'title': 'Whether the sound displays the feature [dorsal_consonantal]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [dorsal_consonantal]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'back',
                                      'title': 'Whether the sound displays the feature [back]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [back]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'close_vocalic_1',
                                      'title': 'Whether the sound displays the feature [close_vocalic_1]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [close_vocalic_1]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'close_vocalic_2',
                                      'title': 'Whether the sound displays the feature [close_vocalic_2]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [close_vocalic_2]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'labial_vocalic',
                                      'title': 'Whether the sound displays the feature [labial_vocalic]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [labial_vocalic]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'coronal_vocalic',
                                      'title': 'Whether the sound displays the feature [coronal_vocalic]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [coronal_vocalic]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'dorsal_vocalic',
                                      'title': 'Whether the sound displays the feature [dorsal_vocalic]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [dorsal_vocalic]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'nasal',
                                      'title': 'Whether the sound displays the feature [nasal]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [nasal]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'lateral',
                                      'title': 'Whether the sound displays the feature [lateral]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [lateral]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'voice',
                                      'title': 'Whether the sound displays the feature [voice]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [voice]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]}]
                                    }
                              },
                              "lexemes": {"path": "LeFFI_lexemes.csv"}
                          },
                          citation="Pellegrini, M. & Cignarella, A. T. (2023). LeFFI 2.0. Online.",
                          version="2.0",
                          keywords=["Italian", "verbs", "paradigms" , "cells"],
                          id="?",
                          contributors=[{'title': 'Matteo Pellegrini', 'role': 'author'},
						  {'title': 'Alessandra T. Cignarella', 'role': 'author'}],
                          licenses=[{'name': 'CC BY-SA 4.0 DEED',
                                     'title': 'Creative Commons Attribution-ShareAlike 4.0 International',
                                     'path': 'https://creativecommons.org/licenses/by-sa/4.0/'}]
)
package.to_json("LeFFI_package.json")