from paralex import paralex_factory

package = paralex_factory("LeFFI",
                          {
                              "forms": {"path": "LeFFI_forms.csv",},
                              "cells": {"path": "LeFFI_cells.csv"},
                              "features-values": {"path": "LeFFI_features-values.csv"},
                              "sounds": {"path": "LeFFI_sounds.csv",
                                "schema": {
                                   "fields": 
[{'name': 'tier',
  'title': 'Tier to which the feature pertains',
  'description': 'Tier to which the feature pertains',
  'type': 'string'},
 {'name': 'value',
  'title': 'Value of the feature',
  'description': 'Value of the feature for non segmental tiers',
  'type': 'string'},
 {'name': 'consonantal',
  'title': 'Whether the sound displays the feature [consonantal]',
  'description': 'Binary feature (1/0) indicating whether the segment displays the feature [consonantal]',
  'type': 'boolean',
  'trueValues': ["1"],
  'falseValues': ["0"]},
 {'name': 'sonorant',
  'title': 'Whether the sound displays the feature [sonorant]',
  'description': 'Binary feature (1/0) indicating whether the segment displays the feature [sonorant]',
  'type': 'boolean',
  'trueValues': ["1"],
  'falseValues': ["0"]},
 {'name': 'approximant',
  'title': 'Whether the sound displays the feature [approximant]',
  'description': 'Binary feature (1/0) indicating whether the segment displays the feature [approximant]',
  'type': 'boolean',
  'trueValues': ["1"],
  'falseValues': ["0"]},
 {'name': 'voice',
  'title': 'Whether the sound displays the feature [voice]',
  'description': 'Binary feature (1/0) indicating whether the segment displays the feature [voice]',
  'type': 'boolean',
  'trueValues': ["1"],
  'falseValues': ["0"]},
 {'name': 'continuant',
  'title': 'Whether the sound displays the feature [continuant]',
  'description': 'Binary feature (1/0) indicating whether the segment displays the feature [continuant]',
  'type': 'boolean',
  'trueValues': ["1"],
  'falseValues': ["0"]},
 {'name': 'nasal',
  'title': 'Whether the sound displays the feature [nasal]',
  'description': 'Binary feature (1/0) indicating whether the segment displays the feature [nasal]',
  'type': 'boolean',
  'trueValues': ["1"],
  'falseValues': ["0"]},
 {'name': 'lateral',
  'title': 'Whether the sound displays the feature [lateral]',
  'description': 'Binary feature (1/0) indicating whether the segment displays the feature [lateral]',
  'type': 'boolean',
  'trueValues': ["1"],
  'falseValues': ["0"]},
 {'name': 'labial_consonantal',
  'title': 'Whether the sound displays the feature [labial_consonantal]',
  'description': 'Binary feature (1/0) indicating whether the segment displays the feature [labial_consonantal]',
  'type': 'boolean',
  'trueValues': ["1"],
  'falseValues': ["0"]},
 {'name': 'coronal',
  'title': 'Whether the sound displays the feature [coronal]',
  'description': 'Binary feature (1/0) indicating whether the segment displays the feature [coronal]',
  'type': 'boolean',
  'trueValues': ["1"],
  'falseValues': ["0"]},
 {'name': 'dorsal_consonantal',
  'title': 'Whether the sound displays the feature [dorsal_consonantal]',
  'description': 'Binary feature (1/0) indicating whether the segment displays the feature [dorsal_consonantal]',
  'type': 'boolean',
  'trueValues': ["1"],
  'falseValues': ["0"]},
 {'name': 'anterior',
  'title': 'Whether the sound displays the feature [anterior]',
  'description': 'Binary feature (1/0) indicating whether the segment displays the feature [anterior]',
  'type': 'boolean',
  'trueValues': ["1"],
  'falseValues': ["0"]},
 {'name': 'syllabic',
  'title': 'Whether the sound displays the feature [syllabic]',
  'description': 'Binary feature (1/0) indicating whether the segment displays the feature [syllabic]',
  'type': 'boolean',
  'trueValues': ["1"],
  'falseValues': ["0"]},
 {'name': 'labial_vocalic',
  'title': 'Whether the sound displays the feature [labial_vocalic]',
  'description': 'Binary feature (1/0) indicating whether the segment displays the feature [labial_vocalic]',
  'type': 'boolean',
  'trueValues': ["1"],
  'falseValues': ["0"]},
 {'name': 'dorsal_vocalic',
  'title': 'Whether the sound displays the feature [dorsal_vocalic]',
  'description': 'Binary feature (1/0) indicating whether the segment displays the feature [dorsal_vocalic]',
  'type': 'boolean',
  'trueValues': ["1"],
  'falseValues': ["0"]},
 {'name': 'high',
  'title': 'Whether the sound displays the feature [high]',
  'description': 'Binary feature (1/0) indicating whether the segment displays the feature [high]',
  'type': 'boolean',
  'trueValues': ["1"],
  'falseValues': ["0"]},
 {'name': 'low',
  'title': 'Whether the sound displays the feature [low]',
  'description': 'Binary feature (1/0) indicating whether the segment displays the feature [low]',
  'type': 'boolean',
  'trueValues': ["1"],
  'falseValues': ["0"]},
 {'name': 'back',
  'title': 'Whether the sound displays the feature [back]',
  'description': 'Binary feature (1/0) indicating whether the segment displays the feature [back]',
  'type': 'boolean',
  'trueValues': ["1"],
  'falseValues': ["0"]}]
                                    }
                              },
                              "lexemes": {"path": "LeFFI_lexemes.csv"}
                          },
                          citation="Pellegrini, M. & Cignarella, A. (2023). LeFFI 2.0. Online.",
                          version="2.0",
                          keywords=["Italian", "verbs", "paradigms" , "cells"],
                          id="?",
                          contributors=[{'title': 'Matteo Pellegrini', 'role': 'author'},
						  {'title': 'Alessandra Cignarella', 'role': 'author'}],
                          licenses=[{'name': 'CC BY-SA 4.0 DEED',
                                     'title': 'Creative Commons Attribution-ShareAlike 4.0 International',
                                     'path': 'https://creativecommons.org/licenses/by-sa/4.0/'}]
)
package.to_json("LeFFI_package.json")